(!label "Overview" 2 "node_chap_1" "1")
(!label "Installation" 3 "node_chap_2" "2")
(!label "Supported Schemes" 3 "node_sec_2.1" "2.1")
(!label "Installing" 3 "node_sec_2.2" "2.2")
(!label "Chicken" 3 "node_sec_2.2.1" "2.2.1")
(!label "Scheme48" 3 "node_sec_2.2.2" "2.2.2")
(!label "Other Schemes" 3 "node_sec_2.2.3" "2.2.3")
(!label "Caveats" 3 "node_sec_2.2.4" "2.2.4")
(!label "Sassy and GNU Emacs" 3 "node_sec_2.3" "2.3")
(!label "Porting Sassy" 3 "node_sec_2.4" "2.4")
(!label "Usage" 4 "node_chap_3" "3")
(!label "dont-expand-tag" 4 "node_tag_Temp_3" "<code class=verbatim>'dont-expand</code>")
(!label "Basic Syntax" 4 "node_sec_3.1" "3.1")
(!label "special-escape" 4 "node_tag_Temp_4" "special escape form")
(!label "escapes" 4 "node_tag_Temp_5" "Escapes")
(!label "escapes2" 4 "node_tag_Temp_6" "escapes")
(!label "Escaping to Scheme" 4 "node_sec_3.2" "3.2")
(!label "Directives" 5 "node_chap_4" "4")
(!label "directive" 5 "node_tag_Temp_7" "directive")
(!label "directives" 5 "node_tag_Temp_8" "directives")
(!label "Label Definitions and Lexical Scoping" 5 "node_sec_4.1" "4.1")
(!label "Defining Labels" 5 "node_sec_4.1.1" "4.1.1")
(!label "Lexical Scoping" 5 "node_sec_4.1.2" "4.1.2")
(!label "The {\\scm{align}} special form" 5 "node_sec_4.2" "4.2")
(!label "Sections" 5 "node_sec_4.3" "4.3")
(!label "Descriptions of directives" 5 "node_sec_4.4" "4.4")
(!label "\\scm{heap}" 5 "node_sec_4.4.1" "4.4.1")
(!label "data-tag" 5 "node_tag_Temp_9" "data")
(!label "\\scm{data}" 5 "node_sec_4.4.2" "4.4.2")
(!label "\\scm{text}" 5 "node_sec_4.4.3" "4.4.3")
(!label "add-sources" 5 "node_tag_Temp_10" "additional sources")
(!label "\\scm{include}" 5 "node_sec_4.4.4" "4.4.4")
(!label "\\scm{import}" 5 "node_sec_4.4.5" "4.4.5")
(!label "\\scm{export}" 5 "node_sec_4.4.6" "4.4.6")
(!label "\\scm{entry}" 5 "node_sec_4.4.7" "4.4.7")
(!label "\\scm{org}" 5 "node_sec_4.4.8" "4.4.8")
(!label "\\scm{macro}" 5 "node_sec_4.4.10" "4.4.10")
(!label "\\scm{begin}" 5 "node_sec_4.4.11" "4.4.11")
(!label "The Text Section" 6 "node_chap_5" "5")
(!label "the-text-section" 6 "node_tag_Temp_11" "The Text Section")
(!label "text section here" 6 "node_tag_Temp_12" "here")
(!label "Instructions" 6 "node_sec_5.1" "5.1")
(!label "instruct1" 6 "node_tag_Temp_13" "Instructions")
(!label "Immediates" 6 "node_sec_5.1.1" "5.1.1")
(!label "Addressing" 6 "node_sec_5.1.2" "5.1.2")
(!label "Operand Sizes" 6 "node_sec_5.1.3" "5.1.3")
(!label "Jumps and Calls" 6 "node_sec_5.1.4" "5.1.4")
(!label "branch-prefix" 6 "node_tag_Temp_14" "see below")
(!label "Prefixes" 6 "node_sec_5.1.5" "5.1.5")
(!label "Assertions" 6 "node_sec_5.2" "5.2")
(!label "Control Primitives" 6 "node_sec_5.3" "5.3")
(!label "The COMFY core" 6 "node_sec_5.3.1" "5.3.1")
(!label "Sassy Extensions" 6 "node_sec_5.3.2" "5.3.2")
(!label "begin text" 6 "node_tag_Temp_15" "additional semantics")
(!label "A Note on Branch Optimization" 6 "node_sec_5.3.3" "5.3.3")
(!label "Raw text data" 6 "node_sec_5.4" "5.4")
(!label "Custom Relocations" 7 "node_chap_6" "6")
(!label "custom-reloc" 7 "node_tag_Temp_16" "Custom Relocations")
(!label "gram-cust-reloc" 7 "node_tag_Temp_17" "<code class=verbatim>&lt;custom-relocation&gt;</code>")
(!label "Output" 8 "node_chap_7" "7")
(!label "output api" 8 "node_tag_Temp_18" "Sassy&#8217;s output API")
(!label "Record-types" 8 "node_sec_7.1" "7.1")
(!label "\\var{sassy-output}" 8 "node_sec_7.1.1" "7.1.1")
(!label "\\var{sassy-symbol}" 8 "node_sec_7.1.2" "7.1.2")
(!label "\\var{sassy-reloc}" 8 "node_sec_7.1.3" "7.1.3")
(!label "sas-reloc" 8 "node_tag_Temp_19" "here")
(!label "Additional procedures for \\var{sassy-output}" 8 "node_sec_7.2" "7.2")
(!label "\\var{push-stacks}" 8 "node_sec_7.3" "7.3")
(!label "Utilities" 8 "node_sec_7.4" "7.4")
(!label "Output Modules" 9 "node_chap_8" "8")
(!label "output module" 9 "node_tag_Temp_21" "output module")
(!label "Flat Binaries" 9 "node_sec_8.1" "8.1")
(!label "ELF Output" 9 "node_sec_8.2" "8.2")
(!label "Macro Expansions" 10 "node_chap_A" "A")
(!label "appendix-a" 10 "node_tag_Temp_22" "Appendix A")
(!label "Supplied macros" 10 "node_sec_A.0.1" "A.0.1")
(!label "Comparisons" 10 "node_sec_A.0.2" "A.0.2")
(!label "More Control Primitives" 10 "node_sec_A.0.3" "A.0.3")
(!label "ELF helpers" 10 "node_sec_A.0.4" "A.0.4")
(!label "cps-macros" 10 "node_tag_Temp_23" "here")
(!label "Explicit Continuation Versions" 10 "node_sec_A.0.5" "A.0.5")
