
(define-library (chibi ai examples iris)
  (import (scheme base)
          (scheme list)
          (scheme read)
          (scheme write)
          (srfi 27)
          (srfi 166)
          (srfi 231)
          (chibi ai nn)
          (chibi ai python)
          (chibi math autodiff)
          (chibi math debug)
          (chibi math linalg)
          (chibi log))
  (export iris-network)
  (include "iris-data.scm" "iris.scm"))
