
(define-library (chibi sqlite3 memoize-test)
  (export run-tests)
  (import (scheme base) (chibi sqlite3 memoize) (chibi test))
  (begin
    (define (run-tests)
      (test-begin "(chibi sqlite3 memoize)")
      (let* ((count 0)
             (fast-length (memoize/sqlite3 (lambda (ls)
                                             (set! count (+ count 1))
                                             (length ls))
                                           ":memory:")))
        (test 0 count)
        (test 0 (fast-length '()))
        (test 1 count)
        (test 0 (fast-length '()))
        (test 1 count)
        (test 1 (fast-length '(1)))
        (test 2 count)
        (test 0 (fast-length '()))
        (test 2 count)
        (test 1 (fast-length '(1)))
        (test 2 count))
      (test-end))))
