(define-library (chibi coding huffman-test)
  (export run-tests)
  (import (scheme base) (chibi coding huffman) (chibi test))
  (begin
    (define (run-tests)
      (test-begin "huffman")
      (let* ((str "banana")
             (huff (make-huffman-code (make-huffman-stats str))))
        (test str (huff 'decode-string (huff 'encode str)))
        (test "ann" (huff 'decode-string (huff 'encode "ann")))
        (test-error (huff 'encode "and")))
      (let* ((ls '(the quick brown fox jumped over the lazy dog))
             (huff (make-huffman-code (make-huffman-stats ls))))
        (test ls (huff 'decode (huff 'encode ls))))
      (test-end))))
